// Raw course data from CSV - will be transformed into Course objects
export const rawCourseData = [
  { name: "Basisprincipes Programmeren", price: 1650, category: "Programmeren & Development" },
  { name: "Python (met ChatGPT)", price: 1575, category: "Programmeren & Development" },
  { name: "Python Deep Learning", price: 3195, category: "AI & Machine Learning" },
  { name: "Werken met Large Language Models in Python", price: 1925, category: "AI & Machine Learning" },
  { name: "Apache Kafka voor Python", price: 1750, category: "DevOps & Containers" },
  { name: "R Programmeren", price: 1925, category: "Programmeren & Development" },
  { name: "Data Analyse", price: 2625, category: "Data & Data Science" },
  { name: "Python voor Data Science", price: 3295, category: "Data & Data Science" },
  { name: "Data Science Management", price: 1200, category: "Data & Data Science" },
  { name: "Data Strategie", price: 1300, category: "Data & Data Science" },
  { name: "Data Modeling", price: 2495, category: "Data & Data Science" },
  { name: "Data Build Tool (dbt)", price: 1750, category: "Data & Data Science" },
  { name: "Apache Airflow", price: 1825, category: "DevOps & Containers" },
  { name: "Anchor Modelling", price: 1395, category: "Data & Data Science" },
  { name: "Data Management DAMA-DMBOK", price: 1875, category: "Data & Data Science" },
  { name: "Big Data", price: 2025, category: "Data & Data Science" },
  { name: "Apache Mahout", price: 2125, category: "AI & Machine Learning" },
  { name: "Apache Pig", price: 1025, category: "Data & Data Science" },
  { name: "Data Mining", price: 1575, category: "Data & Data Science" },
  { name: "Qlik Sense", price: 1695, category: "Data & Data Science" },
  { name: "Google Data Studio", price: 550, category: "Data & Data Science" },
  { name: "Business Objects", price: 1995, category: "Data & Data Science" },
  { name: "Klipfolio", price: 1850, category: "Data & Data Science" },
  { name: "RapidMiner", price: 1425, category: "Data & Data Science" },
  { name: "Infographics", price: 575, category: "Data & Data Science" },
  { name: "SAS", price: 1900, category: "Data & Data Science" },
  { name: "Splunk", price: 1595, category: "Data & Data Science" },
  { name: "IBM Watson Analytics", price: 2195, category: "AI & Machine Learning" },
  { name: "Kunstmatige Intelligentie", price: 950, category: "AI & Machine Learning" },
  { name: "Machine Learning", price: 1800, category: "AI & Machine Learning" },
  { name: "Machine Learning Studio (Azure)", price: 1050, category: "AI & Machine Learning" },
  { name: "Machine Learning met DataRobot", price: 2400, category: "AI & Machine Learning" },
  { name: "Azure Machine Learning", price: 3595, category: "AI & Machine Learning" },
  { name: "TensorFlow", price: 2250, category: "AI & Machine Learning" },
  { name: "AI Automation", price: 1350, category: "AI & Machine Learning" },
  { name: "Hyperautomation", price: 2075, category: "AI & Machine Learning" },
  { name: "Milvus (vector database)", price: 1700, category: "Databases" },
  { name: "AWS Essentials", price: 2125, category: "Cloud Computing" },
  { name: "AWS Cloud Development Kit (CDK)", price: 1995, category: "Cloud Computing" },
  { name: "AWS Monitoring", price: 1350, category: "Cloud Computing" },
  { name: "AWS Security", price: 1995, category: "Beveiliging" },
  { name: "Microsoft Azure", price: 2250, category: "Cloud Computing" },
  { name: "Azure Kubernetes Service (AKS)", price: 1200, category: "DevOps & Containers" },
  { name: "Azure SQL Database", price: 1200, category: "Databases" },
  { name: "Azure Data Factory", price: 1775, category: "Data & Data Science" },
  { name: "Azure Synapse Analytics", price: 2325, category: "Data & Data Science" },
  { name: "Azure DevOps", price: 2125, category: "DevOps & Containers" },
  { name: "Azure Test Plans", price: 1475, category: "DevOps & Containers" },
  { name: "Azure Logic Apps", price: 975, category: "Cloud Computing" },
  { name: "Azure Monitor", price: 1075, category: "Cloud Computing" },
  { name: "Azure Backup", price: 995, category: "Cloud Computing" },
  { name: "Azure Arc", price: 2300, category: "Cloud Computing" },
  { name: "Azure Security Technologies (AZ-500)", price: 2625, category: "Beveiliging" },
  { name: "Windows Virtual Desktop", price: 2475, category: "Cloud Computing" },
  { name: "Microsoft 365 Copilot", price: 625, category: "Cloud Computing" },
  { name: "Microsoft 365 Security", price: 900, category: "Beveiliging" },
  { name: "Microsoft Sentinel", price: 2095, category: "Beveiliging" },
  { name: "SSIS (SQL Server Integration Services)", price: 1675, category: "Databases" },
  { name: "Microsoft Fabric (end-to-end data platform)", price: 1875, category: "Data & Data Science" },
  { name: "Microsoft Fabric met machine learning", price: 2100, category: "AI & Machine Learning" },
  { name: "Microsoft Fabric Data Pipelines", price: 2375, category: "Data & Data Science" },
  { name: "SQL", price: 1050, category: "Databases" },
  { name: "Oracle SQL", price: 1495, category: "Databases" },
  { name: "Oracle Apex Professional", price: 2275, category: "Databases" },
  { name: "Oracle BPM Suite", price: 3475, category: "Programmeren & Development" },
  { name: "Oracle Spatial", price: 2075, category: "Databases" },
  { name: "SQL Server Business Intelligence", price: 3225, category: "Data & Data Science" },
  { name: "MongoDB", price: 3000, category: "Databases" },
  { name: "Redis", price: 1075, category: "Databases" },
  { name: "Performance Tuning in Oracle database", price: 2325, category: "Databases" },
  { name: "Docker", price: 1200, category: "DevOps & Containers" },
  { name: "Docker Enterprise", price: 1200, category: "DevOps & Containers" },
  { name: "Kubernetes voor platform- en cloud engineers", price: 1200, category: "DevOps & Containers" },
  { name: "Kubernetes voor developers (CKAD)", price: 1275, category: "DevOps & Containers" },
  { name: "DevSecOps", price: 875, category: "DevOps & Containers" },
  { name: "PowerShell", price: 775, category: "APIs & Scripting" },
  { name: "API Development", price: 1600, category: "APIs & Scripting" },
  { name: "REST Services", price: 1025, category: "APIs & Scripting" },
  { name: "GraphQL", price: 2250, category: "APIs & Scripting" },
];
