name: E2E Tests

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  e2e-tests:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Setup test database
        run: |
          # Start PostgreSQL container for tests
          docker run -d \
            --name postgres-test \
            -e POSTGRES_PASSWORD=testpassword \
            -e POSTGRES_DB=courseplatform_test \
            -p 5432:5432 \
            postgres:15-alpine

          # Wait for PostgreSQL to be ready
          sleep 5

      - name: Run database migrations
        run: npm run db:migrate:test
        env:
          DATABASE_URL: postgresql://postgres:testpassword@localhost:5432/courseplatform_test

      - name: Seed test database
        run: npm run db:seed:test
        env:
          DATABASE_URL: postgresql://postgres:testpassword@localhost:5432/courseplatform_test

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: postgresql://postgres:testpassword@localhost:5432/courseplatform_test
          NEXTAUTH_SECRET: test-secret-key-for-e2e
          NEXTAUTH_URL: http://localhost:3000
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET: whsec_test_dummy

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          DATABASE_URL: postgresql://postgres:testpassword@localhost:5432/courseplatform_test
          NEXTAUTH_SECRET: test-secret-key-for-e2e
          NEXTAUTH_URL: http://localhost:3000
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: test-results/
          retention-days: 7

      - name: Cleanup
        if: always()
        run: docker stop postgres-test && docker rm postgres-test
